/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c2c9bb",
        "surface-container-highest": "#e3e2e0",
        "primary-container": "#2d5a27",
        "on-error": "#ffffff",
        "secondary-container": "#fadcd3",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary": "#154212",
        "surface-container-low": "#f4f3f1",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f1f1ef",
        "on-tertiary-fixed": "#002107",
        "surface-variant": "#e3e2e0",
        "error": "#ba1a1a",
        "inverse-primary": "#a1d494",
        "surface-dim": "#dadad8",
        "on-secondary-container": "#765f59",
        "tertiary-fixed": "#c5edc1",
        "on-primary-fixed": "#002201",
        "on-surface-variant": "#42493e",
        "on-tertiary-fixed-variant": "#2c4e2e",
        "primary-fixed": "#bcf0ae",
        "background": "#faf9f7",
        "primary-fixed-dim": "#a1d494",
        "on-tertiary-container": "#a6cda3",
        "on-secondary-fixed-variant": "#56423c",
        "tertiary-fixed-dim": "#aad1a7",
        "tertiary": "#1f4022",
        "on-surface": "#1a1c1b",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#23501e",
        "on-background": "#1a1c1b",
        "secondary": "#6f5a53",
        "tertiary-container": "#365837",
        "on-secondary-fixed": "#271813",
        "on-secondary": "#ffffff",
        "outline": "#72796e",
        "inverse-surface": "#2f3130",
        "surface-container-high": "#e9e8e6",
        "surface-container": "#efeeec",
        "surface": "#faf9f7",
        "surface-bright": "#faf9f7",
        "on-primary-container": "#9dd090",
        "on-error-container": "#93000a",
        "surface-tint": "#3b6934",
        "secondary-fixed-dim": "#ddc0b8",
        "secondary-fixed": "#fadcd3",
      },
      fontFamily: {
        "be-vietnam": ["BeVietnamPro_400Regular"],
        "be-vietnam-bold": ["BeVietnamPro_700Bold"],
      },
    },
  },
  plugins: [],
};
